### ISSUE TITLE
CORS header ‘Access-Control-Allow-Origin’ missing?

### ISSUE THREAD

**Issue by Ird3s** [theBowja/starrail-data#2]
> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://starrail-data.vercel.app/api/EN/characters/1001. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 200

I've been receiving this error while trying to fetch anything from the API. 
I'm not sure about it but I believe it's a problem on vercel overwriting cors settings written outside of vercel.json
[Test-cors](https://www.test-cors.org) also returns an error

If that's not the case I'd appreciate if you could explain what I'm doing wrong. 
Thanks in advance

**Comment by theBowja** [comment]
Fixed. Check again

**Comment by Ird3s** [comment]
Thanks. It is now working on latest (https://starrail-data-2addlkd4n-thebowja.vercel.app/) but not on https://starrail-data.vercel.app/

**Comment by theBowja** [comment]
It should auto deploy

**Comment by Ird3s** [comment]
Alright, will close the issue once it does
